"""add kg entity and relationship tables

Revision ID: kg_001
Revises: f1a2b3c4d5e6
Create Date: 2026-07-26

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = "kg_001"
down_revision: str | None = "f1a2b3c4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto-generated by schema inspection ###
    
    # --- kg_entities ---
    op.create_table(
        "kg_entities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_name", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("aliases", JSONB(), nullable=True, server_default="[]"),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("confidence", sa.Float(), nullable=True, server_default="1.0"),
        sa.Column("peer_name", sa.String(), nullable=True),
        sa.Column("mention_count", sa.Integer(), nullable=True, server_default="0"),
        sa.ForeignKeyConstraint(
            ["workspace_name"],
            ["workspaces.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_kg_entities_ws_name", "kg_entities", ["workspace_name", "name"]
    )
    op.create_index(
        "idx_kg_entities_type", "kg_entities", ["workspace_name", "entity_type"]
    )
    op.create_index("idx_kg_entities_name", "kg_entities", ["name"])
    op.create_index("idx_kg_entities_etype", "kg_entities", ["entity_type"])

    # --- kg_relationships ---
    op.create_table(
        "kg_relationships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_name", sa.String(), nullable=False),
        sa.Column("source_entity_id", sa.String(), nullable=False),
        sa.Column("target_entity_id", sa.String(), nullable=False),
        sa.Column("relationship_type", sa.String(), nullable=False),
        sa.Column("properties", JSONB(), nullable=True, server_default="{}"),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("observation_id", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True, server_default="1.0"),
        sa.ForeignKeyConstraint(
            ["workspace_name"],
            ["workspaces.name"],
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id"],
            ["kg_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["kg_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_name",
            "source_entity_id",
            "target_entity_id",
            "relationship_type",
            name="uq_kg_relationship",
        ),
    )
    op.create_index(
        "idx_kg_rel_source", "kg_relationships", ["workspace_name", "source_entity_id"]
    )
    op.create_index(
        "idx_kg_rel_target", "kg_relationships", ["workspace_name", "target_entity_id"]
    )
    op.create_index(
        "idx_kg_rel_type",
        "kg_relationships",
        ["workspace_name", "relationship_type"],
    )
    op.create_index(
        "idx_kg_rel_traverse",
        "kg_relationships",
        ["workspace_name", "relationship_type", "source_entity_id", "target_entity_id"],
    )

    # --- kg_query_log ---
    op.create_table(
        "kg_query_log",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_name", sa.String(), nullable=False),
        sa.Column("query_fingerprint", sa.String(), nullable=False),
        sa.Column("max_depth", sa.Integer(), nullable=True),
        sa.Column("filters_applied", JSONB(), nullable=True, server_default="{}"),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=True, server_default="false"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_kg_query_log_ws", "kg_query_log", ["workspace_name", "created_at"]
    )
    op.create_index(
        "idx_kg_query_fingerprint", "kg_query_log", ["query_fingerprint"]
    )


def downgrade() -> None:
    op.drop_table("kg_query_log")
    op.drop_table("kg_relationships")
    op.drop_table("kg_entities")
